Database init
danielglazer26/internet-databases pull request #2
Opened 2022-11-19 20:15 UTC by M-Szymczyk

Wstępna wersja bazy danych

2022-11-19 20:25 UTC, danielglazer26 requested changes

2022-11-19 20:25 UTC, danielglazer26 commented on Backend/src/main/java/kopaczewski/szymczyk/glazer/estate/portal/RealEstatePortalApplication.java
>  }
wyrzuć

2022-11-19 20:25 UTC, danielglazer26 commented on Backend/src/test/java/kopaczewski/szymczyk/glazer/estate/portal/database/services/PhotoServiceTest.java
> +        try {
Brak koncepcji nazewniczej testu

2022-11-19 20:31 UTC, M-Szymczyk commented on Backend/src/main/java/kopaczewski/szymczyk/glazer/estate/portal/RealEstatePortalApplication.java
>  }
wyrzucone

2022-11-19 20:31 UTC, M-Szymczyk commented on Backend/src/test/java/kopaczewski/szymczyk/glazer/estate/portal/database/services/PhotoServiceTest.java
> +        try {
poprawione

2022-11-19 20:37 UTC, danielglazer26 approved these changes

2022-11-20 10:37 UTC, jarekkopaczewski approved these changes

2022-11-20 10:37 UTC, jarekkopaczewski commented on Backend/src/main/java/kopaczewski/szymczyk/glazer/estate/portal/database/model/Announcement.java
> +    private Double area;
Czym jest area?

2022-11-20 11:36 UTC, merged